name: Test1 - C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v4
    - name: ツールチェーンとライブラリをインストール
      run:  |
        sudo apt-get --yes update
        sudo apt-get --yes install build-essential git libgnutls28-dev libgtkmm-3.0-dev libltdl-dev meson
    - name: JDimをビルド (meson)
      run: meson setup builddir
    - name: JDimをビルド (ninja)
      run: ninja -C builddir
    - name: JDimの起動確認
      run: ./builddir/src/jdim -V
